### ISSUE TITLE
How to dump trained ESN model to disk?

### ISSUE THREAD

**Issue by FajunChen** [cknd/pyESN#3]
I can't dump a trained ESN model to disk. Could you please  help me?

I got this error:
`PicklingError: Can't pickle <function ESN.<lambda> at 0x1a749bb70>: it's not found as ml.train.pyESN.ESN.<lambda>`

**Comment by cknd** [comment]
The proper solution would be to add a save & load method for all the weights (W, W_in, W_out etc) - I'll think about that, but feel free to make PR as well. As a quick solution for pickling: What happens if you replace the two lambda functions in pyESN.py by named functions (i.e. place a `def somename(x): ...` somewhere in the file, and reference this in the places where lambdas are currently used)?

**Comment by cknd** [comment]
I made some [small changes](https://github.com/cknd/pyESN/commit/de294b637450abc072d1e0f49fcca7355450482d) and pickling should now just work^tm

**Comment by JosephDeepIntelli** [comment]
It works. Thank you very much!
