### ISSUE TITLE
Can pyESN fit data online incrementally?

### ISSUE THREAD

**Issue by JosephDeepIntelli** [cknd/pyESN#4]
Theoretically, ESN model could be trained incrementally online. However, It seems that pyESN model does not behavior as expected when I tried to fit in two bathes as compared to fit in a whole batch. Could you please tell me if pyESN model support fitting incrementally or not? Thanks for your excellent work.

**Comment by cknd** [comment]
Hi! Right now, that probably won't work since it's all implemented very naively: [The `fit` method always starts from a 0 state](https://github.com/cknd/pyESN/blob/master/pyESN.py#L178), then [fills a buffer of states the size of the given input](https://github.com/cknd/pyESN/blob/master/pyESN.py#L179-L181) and then [overwrites the weights by the best fit on only the states produced in this call to `fit`](https://github.com/cknd/pyESN/blob/master/pyESN.py#L192-L193). For it to work with small batches (down to N=1) over subsequent calls, it would need to remember the network state between calls to `fit` and use online weight updates. Do you feel up to the task of developing this?
